ARCv3: Replace ARCv2 FPU options with ARCv3 ones
Newer GCC is capable enough to generate FPU instructions for ARCv3
so we need to make sure nSIM is properly set for that.

Otherwise we were seeing the following error from nSIM:
---------------------------->8--------------------------
error: UNREACHABLE CODE: ILLEGAL ARC FPU EXTENSION INSTRUCTION!
---------------------------->8--------------------------